version: "3.7"

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: TECH_ROAD_MAP
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - "./conf:/etc/mysql/conf.d"
      - "./database/TECH_ROAD_MAP/:/var/lib/mysql"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/TECH_ROAD_MAP?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dayoung
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge